config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :albums do |albums|
    resources :images
  end
  root 'albums#index'

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do

     resources :albums do |albums|
        resources :images
     end
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true
  validates_presence_of :attachment
  has_many :images, dependent: :destroy
  belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true
  validates_presence_of :attachment
  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums, dependent: :destroy
  has_many :images, through: :albums
  #attr_protected :admin
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_filter :user_authorize, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /albums
  # GET /albums.json
  def index
    @album = current_user.albums.new
    @albums = Album.all
    respond_to do |format|
      format.html
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show

  end

  # GET /albums/new
  def new
    @album = current_user.albums.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.build(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    def user_authorize
      if current_user != @album.user
        redirect_to root_path, notice: "Sorry it's not your album."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :user_id, :attachment)
    end
end

app/controllers/api/v1/albums_controller.rb
module Api
  module V1
    class AlbumsController < ApplicationController
      respond_to :json

      def index
        @albums = Album.all
      end

      def show
        respond_with Album.find(params[:id])
      end

      def create
        respond_with Album.create(params[:album])
      end

      def update
        respond_with Album.update(params[:album])
      end

      def destroy
        respond_with Album.destroy(params[:id])
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_album, only: [:index, :new, :create, :destroy, :edit, :update]
  before_filter :user_authorize, only: [:new, :edit]
  def index
    @images = @album.images.all
  end

  def new
    @image = @album.images.build
  end

  def edit
    @image = @album.images.find(params[:id])
  end

  def create
    @image = @album.images.build(image_params)

    if @image.save
      redirect_to album_path(@image.album.id), notice: "The image #{@image.name} has been uploaded."
    else
      render "new"
    end
  end

  def update
    @image = @album.images.find(params[:id])
    @image.update(image_params)
    redirect_to album_path(@image.album.id)
  end


  def destroy
    @album = Album.find(params[:album_id])
    @image = @album.images.find(params[:id])
    @image.destroy
    redirect_to album_path(@image.album.id), notice:  "The image #{@image.name} has been deleted."
  end

private
  def image_params
    params.require(:image).permit(:name, :attachment, :album_id)
  end

  def set_album
    @album = Album.find(params[:album_id])
  end
  def user_authorize
    if current_user != @album.user
      redirect_to root_path, notice: "Sorry you can't authorize."
    end
  end

end

app/controllers/task_controller.rb
class TaskController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :set_user
  def index
      if current_person.user.present?
        @users= User.all
      end
      respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @users }
      end
  end
  def show
      @user = User.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
  end
  def new
     if person_signed_in? and current_person.user.present?
       @user = current_person.user
       redirect_to user_timeline_show_path(@user)
     else
     @user = User.new

       respond_to do |format|
         format.html # new.html.erb
         format.json { render json: @user }
       end
     end
  end
  def edit
     @user = User.find(params[:id])
  end
  def create
      @user = User.new(params[:user])
      @user.person = current_person
      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new", errors: @user.errors }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end
  def update
      if @user= current_person.user
        @user = User.find(params[:id])
      end
      @user.person = current_person
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end
  def destroy
      @user = User.find(params[:id])
      if @user == current_person.user
         @user.destroy

        respond_to do |format|
          format.html { redirect_to root }
          format.json { head :no_content }
        end
      end
  end
  protected
      def set_user
         @user = User.find(params[:id])
      end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album.html.erb
<% @albums.each do |album| %>
  <div class="col-lg-3 col-md-4 col-xs-6 thumb">

      <% if album.attachment? %>
        <%= link_to album_path(album) do %>
        <br>
          <%= image_tag album.attachment_url(:thumb), size: "400x200", :class => "img-responsive" %>
        <% end %>
      <% else %>
        <%= image_tag '150x200' , :class => "img-responsive" %>
      <% end %>
        <h2><u><%= album.name %></h2></u>
        <% if current_user == album.user %>
          <%= link_to 'Show', album_path(album), class: "btn btn-success" %>
          <%= link_to 'Edit', edit_album_path(album), class: "btn btn-success" %>
          <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% else %>
          <%= link_to 'Show', album_path(album), class: "btn btn-success" %>
        <% end %>

  </div>
<% end %>
<!-- <div class="col-lg-12">

</div>

<div class="col-lg-3 col-md-4 col-xs-6 thumb">

      <h>Profile Pic</h>
      <h>Album Name</h>
      <h>User name</h>
      <h colspan="3"></h>
    <% @albums.each do |album| %>

        <%= album.attachment %>
        <%= album.name %>
        <%= album.user.email %>
        <% if current_user == album.user %>
        <%= link_to 'Show', album_path(album), class: "btn" %>
        <%= link_to 'Edit', edit_album_path(album), class: "btn" %>
        <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% else %>
        <%= link_to 'Show', album_path(album), class: "btn" %>
        <% end %>
    <% end %>
<% if current_user %>
<%= link_to 'New Album', new_album_path, class: "btn btn-danger" %>
<% end %>

</div>
 -->

app/views/albums/_form.html.erb
<div class ="container" >
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <hr class="colorgraph">
        <%= simple_form_for(@album) do |f| %>
        <div class="form-group">
          <%= f.input :name, input_html: { maxlength: 20 } %>
        </div>
          <%= f.input :attachment %>
          <br>
          <%= f.button :submit, { class: "btn btn-info"} %>
        <% end %>
      </div>
  </div>
</div>

app/views/albums/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
h1 {
     margin-top: 2cm;
}
</style>
</head>
<body>
  <div align= "center">
    <h1>Editing Album</h1>
  </div>
    <%= render 'form' %>
</body>
</html>

app/views/albums/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h1>Album Gallery</h1>
          <% if current_user %>
            <div align="right">
              <%= link_to "Add New Album", new_album_path, class: "btn btn-info" %>
            </div>
            <% end %>
      </div>
      <br>
    </div>
    <%= render "album" %>
  </div>
    <hr>
</div>

app/views/albums/new.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
h1 {
     margin-top: 2cm;
}
</style>
</head>
<body>
<h1 style="text-align:center" >New Album</h1>
</head>
<%= render 'form' %>
</body>
</html>

app/views/albums/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
p {
     margin-top: 2cm;
}
</style>
</head>
<p>
<%= "User id: #{@album.user.email}" %>
  <h2>
    <div align= "center">
      <strong >Album Name:</strong>
      <%= @album.name %>
    </div>
  </h2>

  <% if current_user == @album.user %>
  <br>
    <%= link_to "New Image", new_album_image_path(@album), class: "btn btn-info" %>
  <% end %>
  <br>
    <%= link_to 'Back', albums_path, class: "btn btn-info" %>

  <%= render 'index' %>

<%#= link_to "Images", album_images_path(@album), class: "btn btn-info" %>

</p>
</html>

app/views/application/_footer.html.erb
<!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright © Your Website 2014</p>


                </div>
            </div>
        </footer>

<iframe height="420" allowTransparency="true" frameborder="0" scrolling="no" style="width:420px;border:none" src="http://app.app.localhost:3000/lead_form/c4513329b1c9cd9b1150d72982559657">
<a href="http://app.app.localhost:3000/lead_form/c4513329b1c9cd9b1150d72982559657">Fill out my form!</a></iframe>

app/views/application/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Album store", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <%= render 'devise/sessions/logged_in' %>
      <% else %>
        <%= render 'devise/sessions/new' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/application/_index.html.erb
  <hr>
  <br>
    <% @album.images.each do |image| %>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <%= image_tag image.attachment_url(:thumb).to_s,size: "400x200" , :class => "img-responsive" %>
          <b><%= image.name %></b>
          <% if current_user == @album.user %>
            <%= link_to "Delete",  [image.album, image], method: :delete, data: {confirm:"Are you sure that you wish to delete #{image.name}?"},class: "btn btn-danger" %>
            <%= link_to "Edit", edit_album_image_path(image.album,image), class: "btn btn-success" , method: "get" %>
          <% end %>
      </div>
    <% end %>

app/views/application/_sign_up_page.html.erb
<hr class="colorgraph">
<div class ="container" >
     <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
       <hr class="colorgraph">

       <%= render "devise/registrations/signup" %>

       </div>
    </div>
</div>

app/views/images/_index.html.erb
<hr>
  <br>
    <% @album.images.each do |image| %>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <%= image_tag image.attachment_url(:thumb).to_s,size: "400x200" , :class => "img-responsive" %>
        <b><%= image.name %></b>
        <% if current_user == @album.user %>
        <%= link_to "Delete",  [image.album, image], method: :delete, data: {confirm:"Are you sure that you wish to delete #{image.name}?"},class: "btn btn-danger" %>
        <%= link_to "Edit", edit_album_image_path(image.album,image), class: "btn btn-success" , method: "get" %>
        <% end %>
      </div>
    <% end %>


<!-- <h1><b><%= @album.name %></b></h1>

<pre>
  <%= link_to "Back", albums_path, class: "btn btn-primary" %>
<% if current_user == @album.user %>
  <%= link_to "New Image", new_album_image_path, class: "btn btn-primary" %>
<% end %>
</pre>

<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Images</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.name %></td>
        <td><%= image_tag image.attachment_url %></td>
        <% if current_user == @album.user %>
        <td><%= button_to "Delete",  [image.album, image], method: :delete, data: {confirm:"Are you sure that you wish to delete #{image.name}?"},class: "btn btn-danger" %></td>
        <td><%= button_to "Edit", edit_album_image_path(image.album,image), class: "btn btn-danger" , method: "get" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
 -->

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/edit.html.erb
<hr class="colorgraph">
<div class ="container" >
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
<h1>Editing Images</h1>

<%= simple_form_for @image, :url => {:controller => "images", :action => "update"} do |f| %>
<%= f.input :name, input_html: { maxlength: 20 } %>
<%= f.file_field :attachment %>
<%= f.button :submit %>
<% end %>
    </div>
  </div>
</div>

app/views/images/index.html.erb
<hr>
  <br>
    <% @album.images.each do |image| %>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <%= image_tag image.attachment_url(:thumb).to_s,size: "400x200" , :class => "img-responsive" %>
        <b><%= image.name %></b>
        <% if current_user == @album.user %>
        <%= link_to "Delete",  [image.album, image], method: :delete, data: {confirm:"Are you sure that you wish to delete #{image.name}?"},class: "btn btn-danger" %>
        <%= link_to "Edit", edit_album_image_path(image.album,image), class: "btn btn-success" , method: "get" %>
        <% end %>
      </div>
    <% end %>


<!-- <h1><b><%= @album.name %></b></h1>

<pre>
  <%= link_to "Back", albums_path, class: "btn btn-primary" %>
<% if current_user == @album.user %>
  <%= link_to "New Image", new_album_image_path, class: "btn btn-primary" %>
<% end %>
</pre>

<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Images</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.name %></td>
        <td><%= image_tag image.attachment_url %></td>
        <% if current_user == @album.user %>
        <td><%= button_to "Delete",  [image.album, image], method: :delete, data: {confirm:"Are you sure that you wish to delete #{image.name}?"},class: "btn btn-danger" %></td>
        <td><%= button_to "Edit", edit_album_image_path(image.album,image), class: "btn btn-danger" , method: "get" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
 -->

app/views/images/new.html.erb
<hr class="colorgraph">
<div class ="container" >
     <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
       <hr class="colorgraph">
        <%= simple_form_for @image, :url => {:controller => "images", :action => "create"} do |f| %>

          <%= f.input :name, input_html: { maxlength: 20 }%>
          <%= f.input :attachment %>
          <%= f.button :submit, { class: "btn btn-success"} %>
        <% end %>
       </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlbumStore</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container" style="padding-top:20px;">
      <%= render "header" %>
    <div style="margin:2cm">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
          <a href="#" data-dismiss="alert" class="close">×</a>
            <ul>
              <li>
                <%= msg %>
              </li>
            </ul>
        </div>
      <% end %>
    </div>
      <% if !user_signed_in? %>
        <%= render "sign_up_page" %>
      <% end %>
   </div>
   <%= yield %>
  </body>
</html>


<!-- <div class="alert alert-danger" role="alert">...</div> -->

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>